### PR TITLE
updated the slack.yml file

### LINKED ISSUE #127: to fix error in "Slack Notify on Star" Job under GitHub Actions
**Description**
Under GitHub Actions of this repository "[Slack Notify on Star](https://github.com/meshery/meshery-adapter-library/actions/runs/5435590636)" job is failing for which [Slack.yaml](https://github.com/meshery/meshery-adapter-library/blob/master/.github/workflows/slack.yml) is to be Updated.

**Expected Behavior**

To fix this issue, update the code of [slack.yaml](https://github.com/meshery/meshery-adapter-library/blob/master/.github/workflows/slack.yml)

---
 ### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by captain-Akshay**
**Description**

This PR fixes #127 
 
### Desired State

Under GitHub Actions of this repository "[Slack Notify on Star](https://github.com/meshery/meshery-adapter-library/actions/runs/5435590636)" job is failing for which [Slack.yaml](https://github.com/meshery/meshery-adapter-library/blob/master/.github/workflows/slack.yml) is to be Updated.

**Notes for Reviewers**

To fix this issue, updated the code of [slack.yaml](https://github.com/meshery/meshery-adapter-library/blob/master/.github/workflows/slack.yml)

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by captain-Akshay** [comment]
@saurabh100ni done!
would love to be reviewed!

**Review by Aisuko — COMMENTED** [review]
Hi @captain-Akshay thanks for your contribution. How can I make sure it is work well now?

**Comment by captain-Akshay** [comment]
> Hi @captain-Akshay thanks for your contribution. How can I make sure it is work well now?

Ah it was just copying and pasting if the keys are there in github action then i dont except anything to go wrong 😅 @Aisuko

**Review by Aisuko — APPROVED** [review]
approved

**Comment by Aisuko** [comment]
@captain-Akshay thank you. Here we merge this one first. Please keep following the PR and make sure the effect was made by this PR.

**Comment by captain-Akshay** [comment]
Sure!

**Pull request merged**
