### PR TITLE
[chore] Routine chore

### PR DESCRIPTION
**Pull request by acald-creator**
Signed-off-by: Antonette Caldwell <pullmana8@gmail.com>

**Description**

This PR:
* Remove the `goimports` since it assumes someone has this package installed already.
* `github.com/layer5io/meshkit` upgraded
* `github.com/spf13/viper` upgraded

**Notes for Reviewers**

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by acald-creator** [comment]
// @Revolyssup can you review this and merge?

I will need to open another PR to upgrade to OpenTelemetry packages and it will affect some of the adapters because go.mod will attempt to pull in the latest packages above the `v1.3.0`.

**Comment by acald-creator** [comment]
bump

I will be updating this on a different PR

**Comment by Revolyssup** [comment]
@acald-creator merge confilcts.

**Comment by acald-creator** [comment]
closing this pr, as I opened another one but it is in draft mode https://github.com/meshery/meshery-adapter-library/pull/112

**Pull request closed without merging**
