### PR TITLE
[Lifecycle] Enhance error message for failed installations

### PR DESCRIPTION
**Pull request by theBeginner86**
**Description**

1. This PR adds more fields to the Event stuct so that more information could be shown on the notification center for error messages.
2. New fields added:
- Probable cause
- Suggested remediation 
- Error code
3. Also, updates the meshes/meshops.pb.go so that [EventStreamHandler function](https://github.com/meshery/meshery/blob/78fb25d1d9da53f61e45cbfe0818325acfaaa64e/handlers/events_streamer.go#L25) can pass on this info to the UI.

This PR is related to https://github.com/meshery/meshery-istio/issues/376

**Notes for Reviewers**

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Revolyssup — APPROVED** [review]

**Review by jbyers19 — APPROVED** [review]

**Comment by jbyers19** [comment]
@theBeginner86, would you mind rebasing and squashing your commits before this gets merged?

**Comment by theBeginner86** [comment]
@jbyers19 Done!

BTW even this might not be enough to merge this PR (and its supporting PRs) as I believe that we first need to complete the design spec for the Messaging Framework to be used throughout Meshery.
Link: https://docs.google.com/document/d/1_zpEWBcC6ngOLen_E_nc-octiUdBbpmdwwIX6qzo70M/edit

> Incase, you have any thoughts on the existing work or want to add any of your thoughts then please feel free to chime in 😃

**Comment by jbyers19** [comment]
> @jbyers19 Done!
> 
> BTW even this might not be enough to merge this PR (and its supporting PRs) as I believe that we first need to complete the design spec for the Messaging Framework to be used throughout Meshery. Link: https://docs.google.com/document/d/1_zpEWBcC6ngOLen_E_nc-octiUdBbpmdwwIX6qzo70M/edit
> 
> > Incase, you have any thoughts on the existing work or have suggestions then please feel free to chime in 😃

Ah, I see. Thanks, @theBeginner86. Btw, the lint errors should be fixed in #83.

**Comment by leecalcote** [comment]
A related FYI: on-merge, we don't squash commits.

**Comment by jbyers19** [comment]
@theBeginner86, #83 has been merged so you can pull in those changes and see if they solve your lint errors.

**Pull request closed without merging**
