### PR TITLE
updated dependencies

### PR DESCRIPTION
**Pull request by jbyers19**
**Description**

Updated go version to 1.17 and updated dependencies. 

**Notes for Reviewers**

The open telemetry module has been majorly restructured since this was implemented. I had to update several references in order for them to work.

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by jbyers19** [comment]
@mgfeller, I see you wrote the initial implementation of OTEL. Since then, the OTEL project has been greatly restructured: packages and functions were moved, renamed, or even deleted. I had to update those references accordingly. If you have the time, would you mind taking a look before this gets merged? This is my first time working with the OTEL library and I want to make sure it is correct.

**Review by leecalcote — APPROVED** [review]
Beautiful. Looks good to me.

**Comment by leecalcote** [comment]
@Revolyssup feedback?

**Comment by Revolyssup** [comment]
> @Revolyssup feedback?

@jbyers19  some lint issues I see

**Comment by jbyers19** [comment]
@Revolyssup, yes. Believe those are caused by meshkit. I have opened https://github.com/meshery/meshkit/pull/155 to update that and will update this one that is merged. Hopefully it will resolve the lint issues.

**Comment by Revolyssup** [comment]
> @Revolyssup, yes. Believe those are caused by meshkit. I have opened [meshery/meshkit#155](https://github.com/meshery/meshkit/pull/155) to update that and will update this one that is merged. Hopefully it will resolve the lint issues.



> @Revolyssup, yes. Believe those are caused by meshkit. I have opened [meshery/meshkit#155](https://github.com/meshery/meshkit/pull/155) to update that and will update this one that is merged. Hopefully it will resolve the lint issues.

Will you need meshkit PR to be merged and a release for this?

**Comment by jbyers19** [comment]
@Revolyssup, I believe so, yes. Had to make some changes to the mehskit logger as part of the update, which is what the linter here as complaining about.

**Comment by leecalcote** [comment]
Uh-oh, merge conflict...

**Comment by jbyers19** [comment]
@leecalcote, I will fix the conflicts. However, there must first be a `meshkit` release with the latest changes in order for this PR to work. There was a`v0.5.8` for `meshkit` a few hours ago, but it does not contain the changes needed by this PR.

**Comment by Revolyssup** [comment]
> @leecalcote, I will fix the conflicts. However, there must first be a `meshkit` release with the latest changes in order for this PR to work. There was a`v0.5.8` for `meshkit` a few hours ago, but it does not contain the changes needed by this PR.

Uh oh, I guess we released it 2 hrs before your PR got merged.
Can you confirm that after new release of meshkit, will we also need a simultaneous merge/release of this PR for things to not break? Or just a meshkit release will fix this PR as well as not break any other thing?

**Comment by jbyers19** [comment]
I think it might break things. We should plan to merge them close together. There were some breaking changes by updating from such an old version. Some of the logger references in meshkit had to be refactored to work with the updated library. Those logger references seem to be used by adapter library, hence why meshkit had to be updated first.

**Comment by jbyers19** [comment]
Note: holding off on this until after 0.6.0. Due to the intertwining of dependencies across the projects, making major updates to go versions and dependencies will require a rather large, coordinated effort. Due to the scope of this effort, it will be better to wait until after the release. Closing this PR for now. I'll re-open another one once we are ready to do the update.

**Pull request closed without merging**
