### PR TITLE
Update Meshery Adapter Library  Go version from 1.21 to 1.23

### PR DESCRIPTION
**Pull request by devhindo**
Update the Go version in the go.mod file and CI workflows to ensure compatibility with the latest features and improvements.

fixes: meshery/meshery#12829

### CODE REVIEW

**Comment by devhindo** [comment]
@leecalcote I think this repo needs a fix to allow me to run the workflows? also any review would be appreciated I don't think it needs further changes

**Comment by leecalcote** [comment]
Running build workflow...

**Comment by leecalcote** [comment]
Just as soon as your first PR merges in a given repo, your second PR will automatically approve and trigger the respective workflows.

**Review by leecalcote — CHANGES_REQUESTED** [review]
This file and likely a couple of workflows will need to be updated - https://github.com/meshery/meshery-adapter-library/blob/master/go.mod#L3

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Yay, @devhindo! Your PR has merged and a new version of the library is released. 🎈 https://github.com/meshery/meshery-adapter-library/releases/tag/v0.8.0

**Pull request merged**
